[project]
name = "initializer"
version = "0.1.0"
description = "Initialization script for docker compose"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "letta-client>=0.1.89",
    "requests>=2.32.3",
]
