[project]
name = "derpyrag"
version = "0.1.0"
description = "Hayhooks"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "hayhooks>=0.5.0",
    "pydantic-settings>=2.8.1",
    "tavily-python>=0.5.3",
    "trafilatura>=2.0.0",
]
